"""Revision-3 mutation runner for the C5 hook kit.
Run: C5_REPO=<scratch repo copy> PYTEST=<pytest> python3 this.py [ids]   (set C5_JOBS for parallelism)
Each mutant is applied to a fresh copy by exact single-occurrence substitution (count asserted == 1,
result asserted different) and the whole tests/test_deny_sensitive.py runs in a fresh pytest process.
Tag EQUIV = decision-equivalent on every input (expected to survive); every other mutant must be killed. 'J-' = judge round 1; 'R' = judge round 2; others are mine."""
import os, shutil, subprocess, sys, tempfile
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path
SRC = Path(os.environ.get("C5_REPO", "repo"))
S = "skills/finhub-harness/scripts/deny_sensitive.py"
H = "skills/finhub-harness/references/hooks.md"
K = "skills/finhub-harness/SKILL.md"
F = "skills/finhub-harness/references/surfaces.md"
M = []
def m(id, f, old, new, tag=""): M.append((id, f, old, new, tag))
DENY = 'hit[1][:200]!a}", file=sys.stderr)\n            return 2'
m("deny-exit-2->1", S, DENY, DENY[:-1] + "1")
m("deny-exit-2->0", S, DENY, DENY[:-1] + "0")
m("deny-exit-2->3", S, DENY, DENY[:-1] + "3")
REC = 'nested too deeply; blocking", file=sys.stderr)\n        return 2'
m("recursion-2->1", S, REC, REC[:-1] + "1")
m("recursion-2->0", S, REC, REC[:-1] + "0")
m("recursion-clause-dropped", S, "    except RecursionError:", "    except ZeroDivisionError:")
MAL = 'not blocking", file=sys.stderr)\n        return 1'
m("malformed-1->0", S, MAL, MAL[:-1] + "0")
m("malformed-1->2", S, MAL, MAL[:-1] + "2")
FC = '; blocking", file=sys.stderr)\n        return 2\n    return 0'
m("failclosed-2->0", S, FC, FC.replace("return 2", "return 0"))
m("failclosed-2->1", S, FC, FC.replace("return 2", "return 1"))
m("allow-0->1", S, "    return 0\n\n\nif __name__", "    return 1\n\n\nif __name__")
m("exit-wrapper-dropped", S, "    sys.exit(main())", "    main()")
m("except-Exception->OSError", S, "except Exception as exc:", "except OSError as exc:")
m("J-N10-except-(OSError,ValueError)", S, "except Exception as exc:", "except (OSError, ValueError) as exc:", "EQUIV")
m("parse-except-no-KeyError", S, "except (ValueError, KeyError, TypeError):", "except (ValueError, TypeError):")
m("parse-except-no-TypeError", S, "except (ValueError, KeyError, TypeError):", "except (ValueError, KeyError):")
m("parse-except-no-ValueError", S, "except (ValueError, KeyError, TypeError):", "except (KeyError, TypeError):")
m("tool_input-dict-check-dropped", S, "if not isinstance(tool_input, dict):", "if False:")
m("tool_input-dict-check-inverted", S, "if not isinstance(tool_input, dict):", "if isinstance(tool_input, dict):")
m("stdin-text-not-bytes", S, "sys.stdin.buffer.read()", "sys.stdin.read()")
m("R22-parse_int-dropped", S, ", parse_int=str)", ")")
m("R05-stdin-capped", S, "sys.stdin.buffer.read()", "sys.stdin.buffer.read(1_000_000)")
m("R17-stdin-decode-ignore", S, "json.loads(sys.stdin.buffer.read(), parse_int=str)", 'json.loads(sys.stdin.buffer.read().decode("utf-8", "ignore"), parse_int=str)')
m("reason-repr-not-ascii", S, "{hit[1][:200]!a}", "{hit[1][:200]!r}")
m("reason-untruncated", S, "{hit[1][:200]!a}", "{hit[1][:20000]!a}")
m("R04-reason-last-200", S, "{hit[1][:200]!a}", "{hit[1][-200:]!a}", "EQUIV")
m("deny-to-stdout", S, '{hit[1][:200]!a}", file=sys.stderr)', '{hit[1][:200]!a}")')
m("cwd-ignored", S, 'base = cwd if isinstance(cwd, str) else ""', 'base = ""')
m("cwd-nonstr-accepted", S, 'base = cwd if isinstance(cwd, str) else ""', "base = cwd")
EXP = 'posixpath.join(cwd, expand_vars(os.path.expanduser(raw), MAX_CHARS)).replace("\\\\", "/")'
m("join-dropped", S, EXP, 'expand_vars(os.path.expanduser(raw), MAX_CHARS).replace("\\\\", "/")')
m("J-N03-join-args-swapped", S, EXP, 'posixpath.join(expand_vars(os.path.expanduser(raw), MAX_CHARS), cwd).replace("\\\\", "/")')
m("no-backslash-replace-in-expand", S, EXP, "posixpath.join(cwd, expand_vars(os.path.expanduser(raw), MAX_CHARS))")
m("J-N04-lexical-form-ignores-cwd", S, "text_hit(posixpath.normpath(s))", 'text_hit(posixpath.normpath(expand_vars(os.path.expanduser(raw), MAX_CHARS).replace("\\\\", "/")))')
m("J-N05-resolve-ignores-cwd", S, "real = resolve(s, budget)", 'real = resolve(expand_vars(os.path.expanduser(raw), MAX_CHARS).replace("\\\\", "/"), budget)')
m("no-expanduser", S, "expand_vars(os.path.expanduser(raw), MAX_CHARS)", "expand_vars(raw, MAX_CHARS)")
m("no-expandvars", S, "expand_vars(os.path.expanduser(raw), MAX_CHARS)", "os.path.expanduser(raw)")
m("R01-expand-order-swapped", S, "expand_vars(os.path.expanduser(raw), MAX_CHARS)", "os.path.expanduser(expand_vars(raw, MAX_CHARS))", "EQUIV")
m("command-expandvars-dropped", S, 'WORD_SPLIT.split(expand_vars(cmd.replace("\\\\", "/"), MAX_COMMAND))', 'WORD_SPLIT.split(cmd.replace("\\\\", "/"))')
m("no-normpath", S, "text_hit(posixpath.normpath(s))", "text_hit(s)")
m("pass1-deny-dropped", S, "        if text_hit(posixpath.normpath(s)):\n            return \"sensitive-path\", raw", "        if False:\n            return \"sensitive-path\", raw")
m("no-resolve", S, "real = resolve(s, budget)", "real = s")
m("pass2-todo-dropped", S, "        todo.append((raw, s))", "        pass")
m("no-casefold", S, "f = s.casefold()", "f = s")
m("J-N07-casefold->lower", S, "f = s.casefold()", "f = s.lower()", "EQUIV")
m("R20-casefold-ssh-aws-only", S, "f = s.casefold()", 'f = s.replace("SSH", "ssh").replace("AWS", "aws")')
m("J-N19-resolved-form-not-casefolded", S, "        if text_hit(real):", "        if bool(RE.match(real) or RE.match(real + '/')):")
m("J-N22-dirroot-probe-double-slash", S, 'RE.match(f + "/")', 'RE.match(f + "//")', "EQUIV")
m("no-dirroot-form", S, 'bool(RE.match(f) or RE.match(f + "/"))', "bool(RE.match(f))")
m("no-file-form", S, 'bool(RE.match(f) or RE.match(f + "/"))', 'bool(RE.match(f + "/"))')
m("or-to-and", S, 'bool(RE.match(f) or RE.match(f + "/"))', 'bool(RE.match(f) and RE.match(f + "/"))')
m("re-search", S, 'bool(RE.match(f) or RE.match(f + "/"))', 'bool(RE.search(f) or RE.search(f + "/"))')
m("R07-re-fullmatch", S, 'bool(RE.match(f) or RE.match(f + "/"))', 'bool(RE.fullmatch(f) or RE.fullmatch(f + "/"))', "EQUIV")
m("cap->=", S, "len(raw) > MAX_CHARS", "len(raw) >= MAX_CHARS")
m("cap-4097", S, "MAX_CHARS = 4096", "MAX_CHARS = 4097")
m("cap-4095", S, "MAX_CHARS = 4096", "MAX_CHARS = 4095")
m("J-N06-cap-on-joined-value", S, "if len(raw) > MAX_CHARS:", "if len(posixpath.join(cwd, raw)) > MAX_CHARS:")
m("R15-cap-counts-bytes", S, "if len(raw) > MAX_CHARS:", "if len(raw.encode()) > MAX_CHARS:")
m("cap-applies-to-words-too", S, "            if is_path:\n                return \"too-long\", raw", "            if True:\n                return \"too-long\", raw")
m("cap-skips-paths-too", S, "            if is_path:\n                return \"too-long\", raw", "            if False:\n                return \"too-long\", raw")
m("too-long-returns-None", S, 'return "too-long", raw', "return None")
LW = '            if text_hit(raw):\n                return "sensitive-path", raw\n            continue\n'
m("long-word-text-check-dropped", S, LW, "            continue\n")
m("long-word-always-denied", S, LW, '            return "sensitive-path", raw\n')
m("A33-long-word-gets-full-check", S, LW, '            if text_hit(raw):\n                return "sensitive-path", raw\n')
m("command-cap->=", S, "len(cmd) > MAX_COMMAND", "len(cmd) >= MAX_COMMAND")
m("command-cap-199999", S, "MAX_COMMAND = 200_000", "MAX_COMMAND = 199_999")
m("command-cap-200001", S, "MAX_COMMAND = 200_000", "MAX_COMMAND = 200_001")
m("command-cap-skips-silently", S, '            raise ValueError("command too long")', "            return out")
# budget and link limit (new in r3)
m("budget-16385", S, "MAX_COMPONENTS = 16_384", "MAX_COMPONENTS = 16_385")
m("budget-16383", S, "MAX_COMPONENTS = 16_384", "MAX_COMPONENTS = 16_383")
m("budget-huge", S, "MAX_COMPONENTS = 16_384", "MAX_COMPONENTS = 10**9")
m("budget-tiny", S, "MAX_COMPONENTS = 16_384", "MAX_COMPONENTS = 100")
m("budget-test-<=0", S, "if budget[0] < 0:", "if budget[0] <= 0:")
m("budget-step-2", S, "budget[0] -= 1", "budget[0] -= 2")
m("budget-never-charged", S, "budget[0] -= 1", "pass")
m("budget-per-word", S, "real = resolve(s, budget)", "real = resolve(s, [MAX_COMPONENTS])")
m("budget-exhausted-allows", S, '        except BudgetError:\n            return "path-budget", raw', "        except BudgetError:\n            continue")
m("budget-exhausted-reason", S, 'return "path-budget", raw', 'return "sensitive-path", raw')
m("links-41", S, "MAX_LINKS = 40", "MAX_LINKS = 41")
m("links-39", S, "MAX_LINKS = 40", "MAX_LINKS = 39")
m("links-huge", S, "MAX_LINKS = 40", "MAX_LINKS = 10**9")
m("links->=", S, "if links > MAX_LINKS:", "if links >= MAX_LINKS:")
m("links-not-counted", S, "        links += 1\n", "        links += 0\n")
# resolve semantics
m("resolve-dotdot-no-pop", S, "            if done:\n                done.pop()\n", "            pass\n")
m("resolve-dot-not-skipped", S, 'if name in ("", "."):', 'if name == "":')
m("resolve-empty-not-skipped", S, 'if name in ("", "."):', 'if name == ".":')
m("resolve-absolute-target-keeps-prefix", S, '        if target.startswith("/"):\n            done.clear()\n', "")
m("resolve-target-not-reversed", S, "pending.extendleft(reversed(target.split(\"/\")))", 'pending.extendleft(target.split("/"))')
m("resolve-target-appended", S, "pending.extendleft(reversed(target.split(\"/\")))", 'pending.extend(target.split("/"))')
m("resolve-swallows-ValueError", S, "        except OSError:  # not a link, or missing: a plain component", "        except Exception:  # not a link, or missing: a plain component")
m("resolve-relative-uses-root", S, 'path = os.getcwd() + "/" + path', 'path = "/" + path')
m("resolve-readlink-relative", S, 'os.readlink("/" + "/".join([*done, name]))', 'os.readlink("/".join([*done, name]))')
m("resolve-oserror-narrow", S, "        except OSError:  # not a link, or missing: a plain component", "        except FileNotFoundError:  # not a link, or missing: a plain component")
m("keyword-resolve-link-follow-dropped", S, "        pending.extendleft", "        continue\n        pending.extendleft")
m("hit-always-None-pass2", S, '        if text_hit(real):\n            return "sensitive-path", raw', "        if False:\n            return \"sensitive-path\", raw")
m("rule-call-no-cwd", S, "s = expand(raw, cwd)", 's = expand(raw, "")')
m("candidates-call-empty", S, "candidates(tool_input)", "candidates({})")
m("path-flag-false", S, "out = [(v, True) for k in PATH_KEYS", "out = [(v, False) for k in PATH_KEYS")
m("word-flag-true", S, "out += [(w, False) for w", "out += [(w, True) for w")
for k in ("file_path", "notebook_path", "path"):
    rest = ", ".join(f'"{x}"' for x in ("file_path", "notebook_path", "path") if x != k)
    m(f"key-dropped-{k}", S, 'PATH_KEYS = ("file_path", "notebook_path", "path")', f"PATH_KEYS = ({rest},)")
m("command-key-wrong", S, 'tool_input.get("command")', 'tool_input.get("cmd")')
m("command-nonstr-accepted", S, "if isinstance(cmd, str):", "if cmd:")
m("bash-skipped", S, "out += [(w, False) for w", "out += [] and [(w, False) for w")
m("empty-word-filter-dropped", S, "dict.fromkeys(words) if w]", "dict.fromkeys(words)]")
m("dedupe-dropped", S, "for w in dict.fromkeys(words) if w]", "for w in words if w]")
m("R03-dedupe-sorted-set", S, "for w in dict.fromkeys(words) if w]", "for w in sorted(set(words)) if w]", "EQUIV")
m("R23-dedupe-lowercased", S, "for w in dict.fromkeys(words) if w]", "for w in dict.fromkeys(x.lower() for x in words) if w]")
m("R06-first-1000-words-only", S, "for w in dict.fromkeys(words) if w]", "for w in list(dict.fromkeys(words))[:1000] if w]")
m("backslash-replace-before-split-dropped", S, 'expand_vars(cmd.replace("\\\\", "/"), MAX_COMMAND)', "expand_vars(cmd, MAX_COMMAND)")
m("J-N11-skip-dash-words", S, "dict.fromkeys(words) if w]", 'dict.fromkeys(words) if w and not w.startswith("-")]')
m("J-N12-skip-url-words", S, "dict.fromkeys(words) if w]", 'dict.fromkeys(words) if w and "://" not in w]', "EQUIV")
CLASS = r"[\s;&|()<>`\"'=:,{}]+"
for name, ch in [("whitespace", r"\s"), ("semicolon", ";"), ("amp", "&"), ("pipe", "|"), ("lparen", "("), ("rparen", ")"), ("lt", "<"), ("gt", ">"), ("backtick", "`"), ("dquote", '\\"'), ("squote", "'"), ("equals", "="), ("colon", ":"), ("comma", ","), ("lbrace", "{"), ("rbrace", "}")]:
    m(f"split-class-drops-{name}", S, CLASS, CLASS.replace(ch, "", 1))
m("R02-split-class-no-plus", S, CLASS, CLASS[:-1], "EQUIV")
PATS = ["*/.ssh/*", "*/.aws/*", "*/.config/gcloud/*", "*/.azure/*", "*/.gnupg/*", "*/.docker/config.json", "*/.kube/config", "*/.netrc", "*/_netrc", "*/.npmrc", "*/.pypirc", "*/.git-credentials", "*/id_rsa", "*/id_dsa", "*/id_ecdsa", "*/id_ed25519"]
for p in PATS:
    m(f"pattern-dropped-{p}", S, f'"{p}",', "")
m("aws-two-files", S, '"*/.aws/*"', '"*/.aws/credentials", "*/.aws/config"')
m("aws-one-file", S, '"*/.aws/*"', '"*/.aws/credentials"')
m("docker-widened", S, '"*/.docker/config.json"', '"*/.docker/*"')
m("J-N15-kube-widened-to-any-config", S, '"*/.kube/config"', '"*/config"')
m("kube-widened-to-dir", S, '"*/.kube/config"', '"*/.kube/*"')
m("J-N13-gcloud-widened", S, '"*/.config/gcloud/*"', '"*/gcloud/*"')
m("azure-widened-to-bare", S, '"*/.azure/*"', '"*/azure/*"')
m("R18-azure-narrowed", S, '"*/.azure/*"', '"*/.azure/x"')
m("R19-gnupg-widened", S, '"*/.gnupg/*"', '"*/gnupg/*"')
m("ssh-no-slash", S, '"*/.ssh/*"', '"*/.ssh*"')
m("id_rsa-widened", S, '"*/id_rsa"', '"*/id_rsa*"')
m("R08-id_ed25519-widened", S, '"*/id_ed25519"', '"*/id_ed25519*"')
m("R09-pypirc-widened", S, '"*/.pypirc"', '"*/.pypirc*"')
m("R10-git-credentials-widened", S, '"*/.git-credentials"', '"*/.git-credentials*"')
m("R11-netrc-no-slash", S, '"*/.netrc"', '"*.netrc"')
m("R12-_netrc-no-slash", S, '"*/_netrc"', '"*_netrc"')
m("R13-id_rsa-no-slash", S, '"*/id_rsa"', '"*id_rsa"')
m("stdout-json", S, DENY, DENY.replace("return 2", "print('{}'); return 2"))
# bounded variable expansion (new in r4)
m("expand-bound-dropped", S, "        if size > limit:", "        if False:")
m("expand-bound->=", S, "        if size > limit:", "        if size >= limit:")
m("expand-command-limit-huge", S, "expand_vars(cmd.replace(\"\\\\\", \"/\"), MAX_COMMAND)", "expand_vars(cmd.replace(\"\\\\\", \"/\"), 10**9)")
m("expand-path-limit-huge", S, "expand_vars(os.path.expanduser(raw), MAX_CHARS)", "expand_vars(os.path.expanduser(raw), 10**9)")
m("expand-size-not-grown", S, "        size += len(found) - len(m.group(0))", "        size += 0")
m("expand-size-start-0", S, "    size = len(s)\n", "    size = 0\n")
m("expand-ref-length-ignored", S, "        size += len(found) - len(m.group(0))", "        size += len(found)")
m("expand-braces-not-stripped", S, 'os.environ.get(name[1:-1] if name[0] == "{" else name)', "os.environ.get(name)")
m("expand-unset-vanishes", S, "            return m.group(0)\n        size", "            return \"\"\n        size")
m("expand-not-ascii", S, ', re.ASCII)', ")")
m("expand-environ-key-upper", S, 'os.environ.get(name[1:-1] if name[0] == "{" else name)', 'os.environ.get((name[1:-1] if name[0] == "{" else name).upper())')
# judge round 3 (X-series)
m("X06-dirroot-probe-not-casefolded", S, 'return bool(RE.match(f) or RE.match(f + "/"))', 'return bool(RE.match(f) or RE.match(s + "/"))')
m("X07-path-value-stripped", S, "isinstance(v := tool_input.get(k), str) and v]", "isinstance(v := tool_input.get(k), str) and v.strip()]")
m("X13-command-cap-counts-bytes", S, "if len(cmd) > MAX_COMMAND:", "if len(cmd.encode()) > MAX_COMMAND:")
m("X15-backslash-becomes-space-in-command", S, 'expand_vars(cmd.replace("\\\\", "/"), MAX_COMMAND)', 'expand_vars(cmd.replace("\\\\", " "), MAX_COMMAND)')
m("X17-parse_int-float", S, "parse_int=str", "parse_int=float")
m("X24-pass1-not-casefolded", S, "        if text_hit(posixpath.normpath(s)):", "        if bool(RE.match(posixpath.normpath(s)) or RE.match(posixpath.normpath(s) + '/')):")
m("X02-pass2-first-path-only", S, "    for raw, s in todo:  # pass 2", "    for raw, s in todo[:1]:  # pass 2")
m("X11-split-maxsplit-1000", S, "WORD_SPLIT.split(expand_vars(cmd.replace(\"\\\\\", \"/\"), MAX_COMMAND))", "WORD_SPLIT.split(expand_vars(cmd.replace(\"\\\\\", \"/\"), MAX_COMMAND), maxsplit=1000)")
m("X16-long-word-threshold-plus-1", S, "if len(raw) > MAX_CHARS:", "if len(raw) > MAX_CHARS + 1:")
m("X21-tool_input-default", S, 'payload["tool_input"]', 'payload.get("tool_input", {})')
m("X20-reason-first-line", S, "{hit[1][:200]!a}", "{hit[1].splitlines()[0][:200]!a}", "EQUIV")
# docs (r4)
m("brace-limit-sentence-dropped", H, "brace expansion that splits a name", "brace expansion")
m("brace-example-dropped", H, "`cat ~/.{net,npm}rc`, ", "")
# wiring and host-protocol marks
m("wire-event", H, '"PreToolUse"', '"PostToolUse"')
m("wire-matcher", H, '"matcher": "*"', '"matcher": "Read"')
m("wire-type", H, '"type": "command"', '"type": "prompt"')
m("wire-timeout", H, '"timeout": 10', '"timeout": 600')
m("wire-path", H, '.claude/hooks/deny_sensitive.py\\""', '.claude/hooks/other.py\\""')
m("wire-var", H, '\\"${CLAUDE_PROJECT_DIR}/.claude', '\\"$PWD/.claude')
m("wire-wrapper", H, '"hooks": {\n    "PreToolUse"', '"hook": {\n    "PreToolUse"')
m("J-F6-wire-python3->python", H, 'python3 \\"${CLAUDE_PROJECT_DIR}', 'python \\"${CLAUDE_PROJECT_DIR}')
for row, old in [("Input", "| Unverified: the deepseek bridge builds"), ("Block", "| Unverified: same two sources. |\n| Other"), ("Other", "| Unverified: same two sources. |\n| Stdout"), ("Stdout", "| Unverified: the deepseek decoder only;"), ("Matcher", "| Unverified: seen only in the deepseek bridge;"), ("CommandVariable", "| Unverified: the deepseek bridge and the plugin-dev text only. |"), ("Timeout", "| Unverified. |\n| Several"), ("Several", "| Unverified. |\n| Config"), ("Reload", "| Unverified. |\n| `settings.json`"), ("SettingsShape", "| Unverified until a live check"), ("NestedJson", "| Unverified: assumed, not checked, that the host never sends input this deep"), ("NonString", "| Unverified: assumed, not checked, that the host's own schema")]:
    m(f"mark-dropped-{row}", H, old, old.replace("Unverified", "Checked", 1))
m("flat-claim-readded", H, "is meant to run before the tool does and refuse the call", "is enforced by the host before the tool runs and refuses the call")
m("cowork-flat-claim", H, "on Cowork they are unknown. Treat both", "on Cowork they run no hook. Treat both")
TAIL = "for the credential patterns.\n"
m("B4-slip-appended-to-hooks-md", H, TAIL, TAIL + "\nClaude Code blocks any call whose PreToolUse hook exits 2, and Cowork ignores hooks.\n")
m("B4-slip-in-deny-rules-section", H, "A call is checked when any of these values matches:", "The host's own schema rejects non-strings, so they are ignored. A call is checked when any of these values matches:")
m("B4-skill-line-reworded", K, "ship the credential-path guard in", "ship the enforced credential-path guard in")
m("B4-surfaces-row-reworded", F, "kit in `references/hooks.md`)", "kit in `references/hooks.md`, enforced by Claude Code)")
only = sys.argv[1:]
def one(item):
    id, f, old, new, tag = item
    with tempfile.TemporaryDirectory() as t:
        t = Path(t); shutil.copytree(SRC, t / "r", ignore=shutil.ignore_patterns("__pycache__", ".pytest_cache"))
        p = t / "r" / f; s = p.read_text()
        if s.count(old) != 1: return id, tag, "BAD-ANCHOR(%d)" % s.count(old)
        assert new != old
        p.write_text(s.replace(old, new))
        r = subprocess.run([os.environ.get("PYTEST", "pytest"), "-q", "-x", "-p", "no:cacheprovider", "tests"], cwd=t / "r", capture_output=True, text=True)
        return id, tag, "killed" if r.returncode else "SURVIVED"
items = [x for x in M if not only or x[0] in only]
with ThreadPoolExecutor(int(os.environ.get("C5_JOBS", "4"))) as ex: results = list(ex.map(one, items))
bad = 0
for id, tag, st in results:
    expected_survive = tag in ("EQUIV", "ACCEPTED", "EQUIV-PERF")
    ok = (st == "SURVIVED") if expected_survive else (st == "killed")
    if not ok: bad += 1
    print(("ok   " if ok else "PROBLEM ") + f"{st} {id}" + (f" [{tag}]" if tag else ""))
print(f"mutants run: {len(items)}; problems (survivors, bad anchors, misclassified): {bad}")
