#!/usr/bin/env bash
# usage: proof.sh <root>   (root holds skills/finhub-harness and tests/)
cd "${1:-.}" || exit 2
T=skills/finhub-harness/references/orchestrator-template.md
S=skills/finhub-harness/SKILL.md
U=skills/finhub-harness/references/surfaces.md
n() { printf '%-4s %-3s %s\n' "$1" "$(eval "$2")" "$3"; }
n G01 "grep -c '^10\. \*\*Give every worker a self-contained brief' $T" "expect 1"
n G02 "grep -c '^## Delegation contract (every template that spawns or messages a worker)' $T" "expect 1"
n G03 "grep -c '^\*\*Worker brief\.\*\* The .prompt. of every' $T" "expect 1"
n G04 "grep -c '^- \(Goal\|Inputs\|Scope\|Expected output\|Report\): ' $T" "expect 5"
n G05 "grep -c '^STATUS: complete | partial | blocked$' $T" "expect 1"
n G06 "grep -c '^\(SUMMARY\|EVIDENCE\|NEXT STEPS\|BLOCKER\): ' $T" "expect 4"
n G07 "grep -c '^| complete | EVIDENCE has at least one item, and there is no BLOCKER or NEXT STEPS |$' $T" "expect 1"
n G08 "grep -c '^| partial | NEXT STEPS has at least one item, and there is no BLOCKER |$' $T" "expect 1"
n G09 "grep -c '^| blocked | BLOCKER names something concrete |$' $T" "expect 1"
n G10 "grep -c 'Re-ask once: tell the worker which row it broke' $T" "expect 1"
n G11 "grep -c 'do not ask again: record the result as unverified' $T" "expect 1"
n G12 "grep -c 'for a one-shot worker launch it once more with the same brief' $T" "expect 1"
n G13 "grep -c 'make one second .agent[(][)]. call the same way' $T" "expect 1"
n G14 "grep -c 'A .blocked. report with a concrete BLOCKER is valid' $T" "expect 1"
n G15 "grep -c 'adapted from references/openharness/src/openharness/coordinator/coordinator_mode.py:407 (MIT)' $T" "expect 1"
n G16 "grep -c 'adapted from references/openhands/src/api/launch-child-conversation-client-tool.ts:32 (MIT)' $T" "expect 1"
n G17 "grep -c 'adapted from references/deepseek_harness/packages/workflow/tool-ralph/src/index.ts:112 (MIT)' $T" "expect 1"
n G18 "grep -c 'adapted from references/crewai/lib/crewai/src/crewai/task.py:1327 (MIT)' $T" "expect 1"
n G19 "awk '/^\`\`\`\`markdown/{f=1;next} /^\`\`\`\`\$/{f=0} f' $T | grep -ciE 'based on (your|the) (findings|research)|as (we )?discussed'" "expect 0 (block carries no lazy phrase)"
n G20 "awk '/^## Delegation contract/{a=NR} /^## Follow-up request phrasings/{b=NR} /^9\. \*\*Do not include/{c=NR} /^10\. \*\*Give every/{d=NR} END{print (c<d && d<a && a<b)?\"ordered\":\"BAD\"}' $T" "expect ordered"
n G21 "grep -c '^- \*\*Delegation contract\*\* (only when the orchestrator spawns or messages a worker' $S" "expect 1"
n G22 "grep -c 'WARN .lazy-delegation.)' $S" "expect 1"
n G23 "grep -c \"grep -l 'STATUS:' project/.claude/skills/\*/SKILL.md\" $S" "expect 1"
n G24 "grep -c \"as (we )?discussed' project/.claude/skills/\*/SKILL.md project/.claude/agents/\*.md\" $S" "expect 1"
n G25 "grep -c '^- \[ \] Every worker brief has Goal, Inputs, Scope, Expected output and Report' $S" "expect 1"
n G26 "grep -c '^| 8 | Delegation contract |' $U" "expect 1"
n G27 "grep -nEi 'based on (your|the) (findings|research)|as (we )?discussed' skills/*/SKILL.md .claude/skills/*/SKILL.md .claude/agents/*.md | wc -l" "expect 0 (Step 6 grep on this repo)"
n G28 "wc -l < $S" "expect 200 (<500)"
n G29 "LC_ALL=C.UTF-8 grep -rcP '[\x{AC00}-\x{D7A3}]' $S $T $U skills/finhub-harness/scripts/lint_harness.py tests/test_lint_harness.py tests/fixtures/harness_delegation | awk -F: '{s+=\$NF} END{print s}'" "expect 0 Hangul"
n G30 "grep -c '^\`\`\`\`' $T" "expect 2 (outer copy fence)"
n G31 "grep -c 'Never paste it into a .## Single-context fallback.' $T" "expect 1"
n G32 "grep -c '^One task per call; never send the same task twice\.\$' $T" "expect 1"
n G33 "grep -c 'Workers running in parallel get disjoint scopes' $T" "expect 1"
n G34 "grep -c 'stricter manual fallback' $S" "expect 1 (E5 reworded)"
n G35 "grep -c 'This re-ask is the only retry for an invalid report' $T" "expect 1"
n G36 "grep -c 'never opens it, so an invented path passes' $T" "expect 1"
n G37 "grep -c '\"as discussed\" is not from any reference' $T" "expect 1"
n G38 "grep -c 'prints nothing' $S" "expect 0 (no guarantee a research-and-write skill cannot meet)"
n G39 "grep -c 'which spawns workers briefs them' $S" "expect 0 (old E4 overclaim gone)"
n G40 "grep -c 'agent or skill file which calls' $S" "expect 1"
